### ISSUE TITLE
Tracking Godot 4

### ISSUE THREAD

**Issue by fire** [protongraph/protongraph#101]
Plan a Godot 4 port.

- [ ] plan
- [x] Mesh optimizer is built in.
- [x] GLTF2 module merged.
- [ ] run 3 to 4 tool `https://github.com/godotengine/godot/pull/51950`

# Minimum flow

- [ ] Create a cube
- [ ] Test graph rearrangement

**Comment by Zireael07** [comment]
Any news?

**Comment by fire** [comment]
Seems like ProtonGraph is already on 4.0.
